server:
  port: 8080

spring:
  application:
    name: Farming-App-Backend
  datasource:
    url: jdbc:postgresql://localhost:5432/farmapp
    username: farmapp
    password: farmapp
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update # for dev only; we'll Flyway for prod
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
  flyway:
    enabled: false # will be enable in prod
    #baseline-on-migrate: true
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  issuer: yourFarm
  accessTokenTtlMinutes: 30
  refreshTokenTtlDays: 7
  secret: change-this-in-prod

cors:
  allowed-origins: "http://localhost:4200,https://farmapp.com"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers,threaddump,prometheus
  endpoint:
    health:
      probes:
        enabled: true

frontend:
  base-url: "http://localhost:4200" # https://yourfarm.com used to build checkout success/cancel URLs

# add paymend config
payment:
  stripe:
    secretKey: "sk_live_or_test"
    webhookSecret: "whsec_..."
  paypal:
    clientId: "..."
    clientSecret: "..."
    environment: "sandbox" # or "live"
    webhookId: "..." # PayPal webhook id registered in dashboard
    base-url: "..."
  orangemoney:
    oauth:
      clientId: "..."
      clientSecret: "..."
      tokenUrl: "https://api.orange.com/oauth/v3/token"
    webpay:
      baseUrl: "https://api.orange.com/orange-money-webpay/cm/v1"
      merchantKey: "..." # as per Orange Money docs
      notifUrl: "https://api.yourfarm.com/api/v1/payments/webhooks/orangemoney"
      returnUrl: "https://yourfarm.com/checkout/result"
      signatureSecret: "..." # used to verify callbacks if applicable
  flutterwave:
    baseUrl: "https://api.flutterwave.com/v3"
    secretKey: "FLWSECK-..."
    redirectUrl: "https://yourfarm.com/checkout/result"

